<?php

namespace app\admin\controller;

class Article extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    // 首页
    public function index()
    {
        $data = $this->db->getAll(6);
        $this->assign('data', $data);
        return $this->fetch();
    }
    // 添加
    public function store()
    {
        if(request()->isPost())
        {
            $res = $this->db->store(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $cate = model('Category')->where('des', '<>', '')->order('id', 'asc')->select();
        $this->assign('cate', $cate);
        return $this->fetch();
    }
    // 编辑
    public function edit()
    {
        if(request()->isPost())
        {
            $res = $this->db->edit(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], url('edit',['pid'=>input('param.pid')]));
            }else{
                $this->error($res['msg']);
            }
        }
        $post = $this->db->find(input('param.pid'));
        $this->assign('post', $post);
        $cate = model('Category')->where('des', '<>','')->order('id','asc')->select();
        $this->assign('cate', $cate);
        return $this->fetch();
    }
    // 删除
    public function del()
    {
        $res = $this->db->destray(input('param.pid'));
        if($res['valid'])
        {
            $this->success($res['msg'], 'index');
        }else{
            $this->error($res['msg']);
        }
    }
}
