<?php

namespace app\admin\controller;

class Category extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Category();
    }

    // 首页
	public function index()
	{
		$cate = $this->db->order('id', 'desc')->select();
		$this->assign('list', $cate);
		return $this->fetch();
	}
	// 添加
	public function store()
	{
		if(request()->isPost())
		{
			$res = $this->db->store(input('post.'));
			if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
			    $this->error($res['msg']);
            }
		}
		return $this->fetch();
	}
	// 编辑
    public function edit()
    {
        if(request()->isPost())
        {
            $res = $this->db->edit(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $cate = $this->db->where('id', input('param.id'))->find();
        $this->assign('cate', $cate);
        return $this->fetch();
    }
}
