<?php

namespace app\Admin\controller;

class Link extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Link();
    }

    public function index()
    {
        $field = $this->db->getAll(6);
        $this->assign('link', $field);
        $this->assign('page', $field->render());
        return $this->fetch();
    }
    public function store()
    {
        if(request()->isPost())
        {
            $res = $this->db->store(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }
    public function edit()
    {
        if(request()->isPost())
        {
            $res = $this->db->edit(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
        $link = $this->db->find(input('param.id'));
        $this->assign('link', $link);
        return $this->fetch();
    }
}
