<?php

namespace app\admin\controller;

use think\Controller;

class Rizhi extends Controller
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Rizhi();
    }

    public function index()
    {
        $list = $this->db->order('id', 'DESC')->select();
        $data = [];
        foreach($list as $da)
        {
            $d = json_decode($da['data'], true);
            $data[] = [
                'id'=>$da['id'],
                'time'=>$d['time'],
                'xj1'=>$d['xj1'],
                'xj2'=>$d['xj2'],
                'alipay1'=>$d['alipay1'],
                'alipay2'=>$d['alipay2'],
                'ce1'=>$d['ce1'],
                'ce2'=>$d['ce2'],
                'cdk'=>$d['cdk']
            ];
        }
        $this->assign('rizhi', $data);
        return $this->fetch();
    }

    public function store()
    {
        if(request()->isPost())
        {
            $data = input('post.');
            $data['time'] = time();
            $res = $this->db->store(['data'=>json_encode($data)]);
            if($res)
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
    }
}
