<?php

namespace app\admin\controller;

class Rizhi extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Rizhi();
    }

    public function index()
    {
        $data = $this->db->getAll(6);
        $this->assign('data', $data);
        return $this->fetch();
    }

    public function store()
    {
        if(request()->isPost())
        {
            $res = $this->db->store(input('post.'));
            if($res)
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
        return $this->fetch();
    }

    public function edit()
    {
        if(request()->isPost())
        {}
        $data = $this->db->find(input('param.id'));
        $this->assign('rizhi', $data);
        return $this->fetch();
    }
}
