<?php

namespace app\admin\controller;

class Webset extends Common
{
    protected $db;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Webset();
    }

    public function index()
    {
        $field = $this->db->select();
        $this->assign('setlist', $field);
        return $this->fetch();
    }
    public function edit()
    {
        if(request()->isAjax())
        {
            $res = $this->db->edit(input('post.'));
            if($res['valid'])
            {
                $this->success($res['msg'], 'index');
            }else{
                $this->error($res['msg']);
            }
        }
    }
}
