#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -d ${OPENSHIFT_DATA_DIR}attachment ]; then
    mkdir ${OPENSHIFT_DATA_DIR}attachment
fi

if [ ! -d ${OPENSHIFT_DATA_DIR}cache ]; then
    mkdir ${OPENSHIFT_DATA_DIR}cache
fi

# if [ -f ${OPENSHIFT_DATA_DIR}attachment/20170609/2327c85eb2892ee09c124580910f5b04.jpg ]; then
#	rm ${OPENSHIFT_DATA_DIR}attachment/20170609/2327c85eb2892ee09c124580910f5b04.jpg
# fi
# if [ -f ${OPENSHIFT_DATA_DIR}attachment/20170718/24b862e37197467cf04534731746afb8.jpg ]; then
#    rm ${OPENSHIFT_DATA_DIR}attachment/20170718/24b862e37197467cf04534731746afb8.jpg
# fi

ln -sv ${OPENSHIFT_DATA_DIR}attachment ${OPENSHIFT_REPO_DIR}public

# cp -fv ${OPENSHIFT_REPO_DIR}config.inc.php ${OPENSHIFT_REPO_DIR}blog/config.inc.php

# cp -fv ${OPENSHIFT_REPO_DIR}blog.htaccess ${OPENSHIFT_REPO_DIR}blog/.htaccess


