#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#if [ ${OPENSHIFT_DOCUMENT_ROOT} = "/"]; then
    echo -ne ${OPENSHIFT_DOCUMENT_ROOT}
#fi

if [ ! -d ${OPENSHIFT_DATA_DIR}attachment ]; then
    mkdir ${OPENSHIFT_DATA_DIR}attachment
fi

if [ -f ${OPENSHIFT_DATA_DIR}attachment/20170609/2327c85eb2892ee09c124580910f5b04.jpg ]; then
	rm ${OPENSHIFT_DATA_DIR}attachment/20170609/2327c85eb2892ee09c124580910f5b04.jpg
fi

ln -sv ${OPENSHIFT_DATA_DIR}attachment ${OPENSHIFT_REPO_DIR}

# cp -fv ${OPENSHIFT_REPO_DIR}config.inc.php ${OPENSHIFT_REPO_DIR}blog/config.inc.php

# cp -fv ${OPENSHIFT_REPO_DIR}blog.htaccess ${OPENSHIFT_REPO_DIR}blog/.htaccess


